### PR TITLE
Add Dissect to REMnux

### PR DESCRIPTION
**Pull request by Miauwkeru**
This state file adds the `dissect` suite.

This commit adds:
  - install `python3.9` as its the minimum version that dissect supports. That does mean it does not function on `bionic`.
  - a virtual environment with `dissect` so there are no changes to the system packages.
  - an utility script to `/etc/profile` so you can execute `dissect` in your bash session. This loads both the virtual environment and the auto-completion scripts.
  - install `libfuse2` which is required for `target-mount`.

### CODE REVIEW

**Comment by digitalsleuth** [comment]
Hi @Miauwkeru , unfortunately with Ubuntu Focal, the base version of Python is 3.8, and with Jammy (support coming shortly) it's 3.10, which means that this installation of dissect would be a potentially breaking change. However, I'll take a look at this and see how we can ensure nothing breaks for Focal, and leave Jammy at 3.10.

I'm adding this to testing now.

**Comment by digitalsleuth** [comment]
@Miauwkeru I haven't forgotten about this. Once the existing Python issues are resolved, I'll test this out and see if it works well with the upcoming release.

**Comment by digitalsleuth** [comment]
Hi @Miauwkeru , now that the python issues have been identified / resolved, I've had some time to take a look at this PR. There are a few things which need to be updated to make it function properly, but the majority of what you've done works well.

I'm going to refine the changes and submit a PR with them in the next day or two. Thank you for everything you've done to make sure dissect will work with REMnux!

**Comment by digitalsleuth** [comment]
Hi @Miauwkeru , based on your PR, I've added a PR as #260 which provides some updates to your initial request. Since I can't directly modify your existing PR, I had to submit a new one.

Cheers!

**Comment by lennyzeltser** [comment]
This was addressed via https://github.com/REMnux/salt-states/pull/260, so I'm closing this pull request.

**Pull request closed without merging**
