### PR TITLE
Updated pyinstaller hash

### PR DESCRIPTION
**Pull request by digitalsleuth**
Pyinstaller hash has updated again!

### CODE REVIEW

**Comment by lennyzeltser** [comment]
Thanks, @digitalsleuth. I incorporated this fix into the new release (v2022.17.1).

**Comment by Xboarder56** [comment]
I believe this updated this again, breaking the installs.

https://github.com/extremecoders-re/pyinstxtractor

**Comment by lennyzeltser** [comment]
Thanks for the notification! I will be able to get this fixed at the end of this week.

**Comment by digitalsleuth** [comment]
Hi @Xboarder56 A [pull request](https://github.com/REMnux/salt-states/pull/213) has been submitted to fix this so you're tracking. @lennyzeltser I figured since I just saw this that I'd submit the PR to save you some time.

Cheers!

**Comment by Xboarder56** [comment]
@digitalsleuth @lennyzeltser same issue again guys, they keep updating the hash frequently 

https://github.com/extremecoders-re/pyinstxtractor/blob/master/pyinstxtractor.py

**Comment by Xboarder56** [comment]
This is on a fresh build on a ubuntu-20.04 AMI in AWS via Packer. This is the exact step where it fails when the hash was changing prior. Attached a screenshot of the build failure.

Failed Install

**Comment by lennyzeltser** [comment]
I found an issue with another tool--Anomy--and corrected. Please give it another try.

**Comment by Xboarder56** [comment]
Ohh trying it now, I'll reply back in an hour with the results. Thanks for looking into it.

**Comment by Xboarder56** [comment]
Worked perfectly! thanks for the quick fix

**Pull request merged**
