### PR TITLE
Added MBCScan tool.

### PR DESCRIPTION
**Pull request by accidentalrebel**
Added a new tool called [mbcscan.py](https://github.com/accidentalrebel/mbcscan). Tested working using Remnux's `dev-state.sh`.

Closes https://github.com/REMnux/salt-states/issues/176.

### CODE REVIEW

**Comment by lennyzeltser** [comment]
@accidentalrebel, I'm running issue confirming that the installation works reliably. REMnux includes the Python 2 version of flare-capa as an Ubuntu package, so I'm not inclined to install it again via PIP. Also, as far as I can tell capa (and its dependency Vivisect) have not yet been ported to Python 3.

**Comment by accidentalrebel** [comment]
Good day, Lenny. Hmm. Apologies I only tested the salt states in isolation.

Let me look into this and see if I can figure out ifbit can make use of the Python 2 version of capa. Will update with a new pull request.

Thanks!

**Comment by accidentalrebel** [comment]
@lennyzeltser I just learned that there is now Python 3 support for vivisect starting at version 1.6.0.

More info here: https://github.com/fireeye/capa/releases/tag/v1.6.0

**Comment by lennyzeltser** [comment]
That's great to know! This means that I need to adjust how capa gets installed on REMnux to use Python 3. I encountered an issue with one of its dependencies (when I tried `pip3 install flare-capa`), so will need to set time aside to figure that out.

**Comment by accidentalrebel** [comment]
@lennyzeltser after looking into it a bit more I am afraid that my tool can't be able to use the flare-capa ubuntu binary package. My tool uses flare-capa as a library so it needs the Python3 version for it to work.

I think I know the problem that you speak of when installing `pip3 install flare-capa`. Is this the one where it is encountering an error installing the latest version (1.6.0) so it falls back to an older version (1.3.0)? I learned that this happens because the locale in the docker container is not set. The workaround for this is to run `export LC_ALL=C.UTF-8` first before calling `pip3 install flare-capa`. This would allow the installation to continue.

**Comment by lennyzeltser** [comment]
I'll work on this in the next few days...

**Comment by lennyzeltser** [comment]
@accidentalrebel, it took some doing because of conflicts with other packages, but the Python 3 version of flare is now on REMnux. I added MBCScan (via your Salt state file), too. Thanks!

**Comment by accidentalrebel** [comment]
Yes, I saw the recent commits. I apologize my tool required a lot of changes on your end. Thank you for your work!

Hopefully the inclusion of this tool would help spread awareness about the MBC framework. Thanks!

**Comment by lennyzeltser** [comment]
I appreciated learning from you that the Python 3 version of capa (and vivisect) became available. Once I was able to get them installed, your tool installed very nicely!

**Pull request merged**
