### PR TITLE
Force pip, setuptools, wheel to upgrade above previous vers

### PR DESCRIPTION
**Pull request by digitalsleuth**
With the recent issues in [#148](https://github.com/REMnux/remnux-cli/issues/148), [#142](https://github.com/REMnux/remnux-cli/issues/142) and [254](https://github.com/REMnux/salt-states/issues/254), it seems like they're all linked by setuptools and wheel, given recent changes to their requirements for the installation of pip packages.

To this end, this PR will remove the restriction on version for both of these states, and re-add ioc-parser, malchive, and virustotal-api'.

This fix should alleviate any upgrade issues, and prevent any further initial installation issues.

### CODE REVIEW

**Comment by lennyzeltser** [comment]
Thank you very much, @digitalsleuth! I just incorporated this into a new release. However, running `remnux upgrade` with it produces several errors. I won't get a chan
[saltstack.log](https://github.com/REMnux/salt-states/files/12585795/saltstack.log)
ce to troubleshoot them today, but I wanted to attach the saltstack.log file in case you will get a chance to review it.

**Comment by digitalsleuth** [comment]
Of course, test 20 times and everything's fine. It's that 21st time you gotta watch out for. Hahah. I'll take a look at the log now to see what's happening.

**Comment by digitalsleuth** [comment]
The issue is that the existing pip, wheel, and setuptools are still at the previous versions and didn't upgrade. I'll have to add a "force_reinstall: True" to those states to make it work. Unfortunately, I'm not at home right now and won't be able to do this until later.

**Comment by seanthegeek** [comment]
I just tried to manually force an upgrade of setuptools. It downloaded setuptools 68.2.2 and somehow, it still installed setuptools-60.8.0

```
sudo pip install --break-system-packages --force-reinstall --upgrade pip wheel setuptools
[sudo] password for remnux: 
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/50/c2/e06851e8cc28dcad7c155f4753da8833ac06a5c704c109313b8d5a62968a/pip-23.2.1-py3-none-any.whl.metadata
  Downloading pip-23.2.1-py3-none-any.whl.metadata (4.2 kB)
Collecting wheel
  Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
  Downloading wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
Collecting setuptools
  Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl.metadata
  Downloading setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 11.4 MB/s eta 0:00:00
Downloading wheel-0.41.2-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 12.9 MB/s eta 0:00:00
Downloading setuptools-68.2.2-py3-none-any.whl (807 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 18.6 MB/s eta 0:00:00
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: wheel
    Found existing installation: wheel 0.36.2
    Uninstalling wheel-0.36.2:
      Successfully uninstalled wheel-0.36.2
  Attempting uninstall: setuptools
    Found existing installation: setuptools 60.7.1
    Uninstalling setuptools-60.7.1:
      Successfully uninstalled setuptools-60.7.1
  Attempting uninstall: pip
    Found existing installation: pip 23.2
    Uninstalling pip-23.2:
      Successfully uninstalled pip-23.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.
speakeasy-emulator 1.5.11 requires unicorn==1.0.2, but you have unicorn 2.0.1.post1 which is incompatible.
thug 5.0.1 requires charset-normalizer==3.1.0, but you have charset-normalizer 2.1.1 which is incompatible.
thug 5.0.1 requires cssutils==2.6.0, but you have cssutils 2.7.1 which is incompatible.
thug 5.0.1 requires requests-futures==1.0.0, but you have requests-futures 1.0.1 which is incompatible.
Successfully installed pip-23.2.1 setuptools-60.8.0 wheel-0.41.2
```

**Comment by seanthegeek** [comment]
It turns out that I somehow had multiple versions of setuptools installed. I had to manually remove those to be able to upgrade it.

```
remnux@remnux:~$ sudo ls /usr/local/lib/python3.8/dist-packages/setuptools-*
setuptools-60.7.1.dist-info/ setuptools-61.3.0.dist-info/
setuptools-60.8.0.dist-info/ setuptools-65.7.0.dist-info/
setuptools-60.8.2.dist-info/ setuptools-67.8.0.dist-info/
setuptools-60.9.3.dist-info/ setuptools-68.0.0.dist-info/
remnux@remnux:~$ sudo rm -rf /usr/local/lib/python3.8/dist-packages/setuptools-6*
remnux@remnux:~$ sudo pip install --break-system-packages --force-reinstall setuptools pip wheel
Collecting setuptools
  Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl.metadata
  Downloading setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/50/c2/e06851e8cc28dcad7c155f4753da8833ac06a5c704c109313b8d5a62968a/pip-23.2.1-py3-none-any.whl.metadata
  Downloading pip-23.2.1-py3-none-any.whl.metadata (4.2 kB)
Collecting wheel
  Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
  Downloading wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
Downloading setuptools-68.2.2-py3-none-any.whl (807 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 8.5 MB/s eta 0:00:00
Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 13.6 MB/s eta 0:00:00
Downloading wheel-0.41.2-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 12.3 MB/s eta 0:00:00
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: wheel
    Found existing installation: wheel 0.36.2
    Uninstalling wheel-0.36.2:
      Successfully uninstalled wheel-0.36.2
  Attempting uninstall: setuptools
    Found existing installation: setuptools 52.0.0
    Uninstalling setuptools-52.0.0:
      Successfully uninstalled setuptools-52.0.0
  Attempting uninstall: pip
    Found existing installation: pip 23.2
    Uninstalling pip-23.2:
      Successfully uninstalled pip-23.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.
speakeasy-emulator 1.5.11 requires unicorn==1.0.2, but you have unicorn 2.0.1.post1 which is incompatible.
thug 5.0.1 requires charset-normalizer==3.1.0, but you have charset-normalizer 2.1.1 which is incompatible.
thug 5.0.1 requires cssutils==2.6.0, but you have cssutils 2.7.1 which is incompatible.
thug 5.0.1 requires requests-futures==1.0.0, but you have requests-futures 1.0.1 which is incompatible.
Successfully installed pip-23.2.1 setuptools-68.2.2 wheel-0.41.2
```

**Pull request merged**
