### PR TITLE
Add the Sleuthkit toolset

### PR DESCRIPTION
**Pull request by kouril**
The Sleuthkit contains essential tools to analyze volumes and filesystem. I was a bit surprised it was missing from REMnux :-)

### CODE REVIEW

**Comment by digitalsleuth** [comment]
Hi @kouril, we had discussed this originally when building this version, however we had decided against it. As REMnux is built to be a malware analysis toolset, the Sleuthkit would very rarely be used. The idea being that you would likely import your binary or memory dump into REMnux to begin your analysis.

Additionally, since REMnux has been built to be compatible with SIFT, you could install SIFT alongside REMnux in your environment. This would add the Sleuthkit to your environment, and ensure that it's up-to-date with each SIFT upgrade.

**Comment by kouril** [comment]
I see the point and realize that general forensics is probably not the scope of REMnux, however (whether you want it or not :-) I find it very useful also for this type of analysis. The big advantage here is that I can use the same environment for detecting/extracting the evidence and its further analysis. I certainly can (and do) install needed tools as i need them (and utilize the pre-defined repositories) but the Sleuthkit toolkit is something I use for every investigation so I thought it could be useful for others as well.

As for SIFT and the like, I find extremely convenient the Docker container, which is way more flexible then a full VM. I'm not sure how/if SIFT can be used as a container.

That said, if you decide Sleuthkit is against to what you like REMnux to be, I'm fine with that. REMnux is a cool product and I'll happily keep using it, thanks for it.

**Comment by digitalsleuth** [comment]
@kouril You can actually use SIFT and REMnux as dockers. I have one built which combines both, and it can be found in the hub.docker.com repo under digitalsleuth/sift-remnux. 

The final decision on Sleuthkit is up to @lennyzeltser of course, so I would obviously go with his decision. But in the meantime, the sift-remnux docker might fit your needs, or you could use the Dockerfile for the REMnux docker and customize it to include Sleuthkit.

I hope this helps!

**Comment by lennyzeltser** [comment]
First of all, @kouril, thank you for creating this pull request, and doing this in a way that matches the REMnux approach to Salt state files! It's very tempting to accept the pull request. I really appreciate the help!

Based on your justification, I recognize the usefulness of Sleuthkit as a starting point for malware investigations. It's not a heavy tool, so it wouldn't add a lot to the disk space requirements. However, I see that the the version of Sleuthkit that comes from the standard Ubuntu repositories is a bit dated. SIFT, in contrast, seems to provide its own version of Sleuthkit from its repo, and also includes some config files for this set of tools.

So including Sleuthkit in REMnux would require more than installing its version from the default Ubuntu repo, and would involve additional maintenance tasks. Therefore, at this point I'd prefer to not include it. Let's see if the need for this tool in REMnux resurfaces based on requests from additional community members.

**Comment by lennyzeltser** [comment]
After some discussion with @digitalsleuth, we agreed to follow your recommendation and add Sleuthkit to REMnux. We'll go with the SIFT approach by getting it from the [GIFT](https://launchpad.net/~gift) repo, so we get the latest version of the tool.

**Comment by lennyzeltser** [comment]
Done. Sleuthkit is now a part of REMnux. Thanks for your suggestion and the Salt state file, @kouril!

**Pull request merged**
